"glb"="ï†²"
"lua"="î˜ "
"cmake"="î˜•"
"hh"="ïƒ½"
"dockerfile"="î°"
"py"="î˜†"
".bashrc"="î˜•"
"gulpfile"="î˜"
"cp"="î˜"
"Brewfile"="î‘"
"makefile"="î˜•"
"vim"="î˜«"
"Vagrantfile$"="ïŠ¸"
"COPYING.LESSER"="î˜Š"
"mdx"="î˜‰"
"ex"="î˜­"
"opus"="ïœ¢"
"Rmd"="î˜‰"
"pp"="î˜±"
"fsscript"="î§"
"sqlite3"="îœ†"
"jsx"="î˜¥"
"fsx"="î§"
"_gvimrc"="î˜«"
"jpeg"="î˜"
"sh"="î•"
"go"="î˜§"
"html"="î˜"
"lhs"="î˜Ÿ"
"cljc"="î¨"
"cljs"="îª"
"elm"="î˜¬"
"R"="ï³’"
".npmrc"="îœ"
".gitconfig"="î˜•"
"rs"="î¨"
"sublime"="îª"
"Gemfile$"="î‘"
"json"="î˜‹"
"edn"="îª"
"zsh"="î•"
"cr"="î‰"
"awk"="î•"
"fsi"="î§"
"mli"="Î»"
"node_modules"="îœ˜"
"LICENSE"="î˜Š"
"CMakeLists.txt"="î˜•"
"terminal"="ï’‰"
".gitmodules"="îœ‚"
"hbs"="î˜"
"sol"="ï²¹"
"zig"="ïƒ§"
"mint"="ï ©"
"package-lock.json"="îœ"
".ds_store"="î˜•"
"pyd"="î˜†"
"conf"="î˜•"
"xul"="î…"
"license"="î˜Š"
"ai"="î´"
"leex"="î˜­"
"mjs"="î˜Œ"
"ppt"="ïœ¦"
"eex"="î˜­"
"xml"="ïª¿"
"xls"="ïœš"
"exs"="î˜­"
"rb"="î‘"
"cson"="î˜‹"
"ejs"="î˜"
"h"="ïƒ½"
"xcplayground"="î•"
"rakefile"="î‘"
"c"="î˜"
"d"="î¯"
"webp"="î˜"
"pl"="î©"
"clj"="î¨"
"vue"="ïµ‚"
"cpp"="î˜"
"hrl"="î±"
"coffee"="î˜›"
"hpp"="ïƒ½"
"txt"="ïœ˜"
"godot"="î£"
"twig"="î˜œ"
"erl"="î±"
"tscn"="ï¢€"
"ts"="î˜¨"
"rake"="î‘"
"tres"="îœ†"
"COMMIT_EDITMSG"="îœ‚"
"toml"="î˜•"
"cfg"="î£"
"tex"="ï­¨"
"t"="î©"
"desktop"="ï„ˆ"
"fish"="î•"
"swift"="î•"
"bash"="î•"
"svg"="ï°Ÿ"
".gitattributes"="îœ‚"
".vimrc"="î˜«"
"cbl"="âš™"
"hxx"="ïƒ½"
"nix"="ïŒ“"
"jl"="î˜¤"
"psd"="î¸"
"suo"="îœŒ"
"styl"="î˜€"
"c++"="î˜"
"cobol"="âš™"
"pyo"="î˜†"
"sql"="îœ†"
"cc"="î˜"
"git"="îœ‚"
"COPYING"="î˜Š"
"sml"="Î»"
".zprofile"="î˜•"
"_vimrc"="î˜«"
"sln"="îœŒ"
"kt"="ğ™†"
"gif"="î˜"
"gruntfile"="î˜‘"
".bash_profile"="î˜•"
"sig"="Î»"
"bat"="î˜•"
"js"="î˜Œ"
"pyc"="î˜†"
"dart"="î˜"
"scss"="î˜ƒ"
"fs"="î§"
".gitlab-ci.yml"="ïŠ–"
"ini"="î˜•"
"cs"="ï š"
"md"="î˜‰"
"otf"="ï€±"
"rss"="î˜™"
"psb"="î¸"
"rproj"="ï«…"
"less"="î˜”"
"pck"="ï’‡"
"rmd"="î˜‰"
"haml"="î˜"
"rlib"="î¨"
"webpack"="ï°©"
"r"="ï³’"
".zshenv"="î˜•"
"erb"="î˜"
"svelte"="ï‰ "
"slim"="î˜"
"ico"="î˜"
"procfile"="î˜‡"
"cob"="âš™"
"png"="î˜"
"pm"="î©"
"webmanifest"="î˜‹"
"php"="î˜ˆ"
"pdf"="ïœ¤"
".settings.json"="îœŒ"
"yaml"="î˜•"
"package.json"="îœ"
"sass"="î˜ƒ"
".zshrc"="î˜•"
"diff"="îœ¨"
"nim"="ğŸ‘‘"
"mustache"="î˜"
"ml"="Î»"
"mix.lock"="î˜­"
"yml"="î˜•"
"cpy"="âš™"
".npmignore"="îœ"
"tsx"="îº"
"markdown"="î˜‰"
"ps1"="î•"
"ksh"="î•"
"jpg"="î˜"
"java"="îœ¸"
"config.ru"="î‘"
"scala"="îœ·"
"import"="ïƒ†"
"Dockerfile"="î°"
"htm"="î˜"
"hs"="î˜Ÿ"
"heex"="î˜­"
"gemspec"="î‘"
".babelrc"="ï¬¥"
"gd"="î˜•"
"css"="î˜”"
"favicon.ico"="î˜£"
"material"="ïŸ´"
"f#"="î§"
"epp"="î˜±"
"csv"="ïœ˜"
"dump"="îœ†"
"pro"="î¡"
".gitignore"="îœ‚"
"doc"="ïœ«"
"db"="îœ†"
"cxx"="î˜"
"csh"="î•"
".gvimrc"="î˜«"
"dropbox"="îœ‡"
"sqlite"="îœ†"
"bmp"="î˜"
