"attribute" = "#dbbfef" # lilac
"keyword" = "#eccdba" # almond
"keyword.directive" = "#dbbfef" # lilac -- preprocessor comments (#if in C)
"namespace" = "#dbbfef" # lilac
"punctuation" = "#a4a0e8" # lavender
"punctuation.delimiter" = "#a4a0e8" # lavender
"operator" = "#dbbfef" # lilac
"special" = "#efba5d" # honey
# "property" = "#a4a0e8" # lavender
"property" = "#ffffff" # white
"variable" = "#a4a0e8" # lavender
# "variable" = "#eccdba" # almond TODO: metavariables only
"variable.parameter" = "#a4a0e8" # lavender
# TODO distinguish type from type.builtin?
"type" = "#ffffff" # white
"type.builtin" = "#ffffff" # white
"constructor" = "#dbbfef" # lilac
"function" = "#ffffff" # white
"function.macro" = "#dbbfef" # lilac
"function.builtin" = "#ffffff" # white
"comment" = "#697C81" # sirocco
"variable.builtin" = "#9ff28f" # mint
"constant" = "#ffffff" # white
"constant.builtin" = "#ffffff" # white
"string" = "#cccccc" # silver
"number" = "#e8dca0" # chamois
"escape" = "#efba5d" # honey
# used for lifetimes
"label" = "#efba5d" # honey

# TODO: diferentiate number builtin
# TODO: diferentiate doc comment
# TODO: variable as lilac
# TODO: mod/use statements as white
# TODO: mod stuff as chamois
#
# concat (ERROR) @syntax-error and "MISSING ;" selectors for errors

"module" = "#ff0000"

"ui.background" = { bg = "#3b224c" } # midnight
"ui.linenr" = { fg = "#5a5977" } # comet
"ui.statusline" = { bg = "#281733" } # revolver
"ui.popup" = { bg = "#281733" } # revolver
"ui.window" = { bg = "#452859" } # bossa nova
"ui.window" = { bg = "#452859" } # bossa nova
"ui.help" = { bg = "#6F44F0", fg = "#a4a0e8" }
"ui.help" = { bg = "#7958DC", fg = "#171452" }

"ui.text" = { fg = "#a4a0e8" } # lavender
"ui.text.focus" = { fg = "#dbbfef"} # lilac

"ui.menu.selected" = { fg = "#281733", bg = "#ffffff" } # revolver

"warning" = "#ffcd1c"
"error" = "#f47868"
"info" = "#6F44F0"
"hint" = "#cccccc"
