# Author: Two-Six<twopsix@duck.com>

"ui.background" = {bg="acme_bg"}
"ui.text" = "black"
"ui.linenr" = {bg="acme_bg", fg="black"}
"ui.linenr.selected" = {bg="acme_bg", fg="black"}
"ui.selection" = {bg="selected"}
"ui.cursorline" = {bg="acme_bar_bg"}
"ui.statusline" = {fg="black", bg="acme_bar_bg"}
"ui.statusline.inactive" = {fg="black", bg="acme_bar_inactive"}
"ui.virtual" = "indent"
"ui.virtual.ruler" = { bg = "acme_bar_bg" }
"ui.cursor.match" = {bg="acme_bar_bg"}
"ui.cursor" = {bg="cursor", fg="white"}
"ui.debug" = {fg="orange"}
"ui.highlight.frameline" = {bg="#da8581"}
"string" = "red"
"comment" = "green"
"ui.help" = {fg="black", bg="acme_bg"}
"ui.popup" = {fg="black", bg="acme_bg"}
"ui.menu" = {fg="black", bg="acme_bg"}
"ui.menu.selected" = {bg="selected"}
"ui.window" = {bg="acme_bg"}
"diagnostic.error" = {bg="red", fg="white", modifiers=["bold"]}
"diagnostic.warning" = {bg="orange", fg="black", modifiers=["bold"]}
"diagnostic.hint" = {fg="gray", modifiers=["bold"]}
"ui.bufferline" = { fg = "black", bg = "acme_bar_bg" }
"ui.bufferline.active" = { fg = "black", bg = "acme_bg" }
"diff.plus" = {fg = "green"}
"diff.delta" = {fg = "acme_bar_bg"}
"diff.minus" = {fg = "red"}

[palette]
white = "#ffffff"
acme_bg = "#ffffea"
black = "#000000"
selected = "#eeee9e"
acme_bar_bg = "#aeeeee"
acme_bar_inactive = "#eaffff"
cursor = "#444444"
red = "#a0342f"
green = "#065905"
indent = "#aaaaaa"
orange = "#f0ad4e"
gray = "#777777"
