# The structure is based on `base16_default_dark` by Ray Gervais.  Most of
# the colors come the so called Autumn theme, a color scheme inspired by
# the colors you can find in autumn. Originally it was designed as a
# color scheme for the Komodo IDE and then ported to Vim by Kenneth Love
# and Chris Jones. Later, Yorick Peterse improved their work. See:
# <https://github.com/YorickPeterse/Autumn.vim>
# Jens Getreu finally ported and optimised the color theme for the Helix editor.
# Author: Jens Getreu <getreu at web.de>

"ui.background" = { bg = "my_gray0" }
"ui.menu" = { fg = "my_white", bg = "my_gray2" }
"ui.menu.selected" = { fg = "my_gray2", bg = "my_gray5" }
"ui.linenr" = { fg = "my_gray4", bg = "my_gray2" }
"ui.popup" = { bg = "my_gray2" }
"ui.window" = { bg = "my_gray2" }
"ui.linenr.selected" = { fg = "my_gray5", bg = "my_gray2", modifiers = ["bold"] }
"ui.selection" = { bg = "my_gray3" }
"comment" = { fg = "my_gray4", modifiers = ["italic"] }
"ui.statusline" = { fg = "my_gray5", bg = "my_gray2" }
"ui.help" = { fg = "my_gray5", bg = "my_gray2" }
"ui.cursor" = { fg = "my_gray5", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "my_white", modifiers = ["reversed"] }
"ui.text" = "my_white"
"operator" = "my_white"
"ui.text.focus" = "my_white"
"variable" = "my_white3"
"constant.numeric" = "my_turquoise"
"constant" = "my_white3"
"attributes" = "my_turquoise"
"type" = { fg = "my_white3", modifiers = ["italic"] }
"ui.cursor.match" = { fg = "my_white3", modifiers = ["underlined"] }
"string"  = "my_green"
"variable.other.member" = "my_brown"
"constant.character.escape" = "my_turquoise"
"function" = "my_yellow1"
"constructor" = "my_yellow1"
"special" = "my_yellow1"
"keyword" = "my_red"
"label" = "my_red"
"namespace" = "my_white3"
"ui.help" = { fg = "my_gray6", bg = "my_gray2" }
"ui.virtual.whitespace" = { fg = "my_gray5" }
"ui.virtual.ruler" = { bg = "my_gray1" }

"markup.heading" = "my_yellow1"
"markup.list" = "my_white2"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = {  modifiers = ["italic"] }
"markup.link.url" = "my_turquoise2"
"markup.link.text" = "my_white2"
"markup.quote" = "my_brown"
"markup.raw" = "my_green"

"diff.plus" = "my_green"
"diff.delta" = "my_white"
"diff.minus" = "my_red"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "my_gray2" }
"hint" = "my_gray5"
"debug" = "my_yellow2"
"info" = "my_yellow2"
"warning" = "my_yellow2"
"error" = "my_red"

[palette]
my_gray0      = "#292929" # Default Background
my_gray1      = "#2e2e2e" # Ruler
my_gray2      = "#3a3a3a" # Lighter Background (Used for status bars, line number and folding marks)
my_gray3      = "#525252" # Selection Background
my_gray4      = "#7c7c7c" # Comments, Invisibles, Line Highlighting
my_gray5      = "#aaaaaa" # Dark Foreground (Used for status bars)
my_gray6      = "#e8e8e8" # Light Foreground (Not often used)
my_gray7      = "#f8f8f8" # Light Background (Not often used)
my_white      = "#F3F2CC" # Default Foreground, Caret, Delimiters, Operators
my_white2     = "#F3F2CC" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
my_white3     = "#F3F2CC" # Classes, Markup Bold, Search Text Background
my_turquoise  = "#86c1b9" # Support, Regular Expressions, Escape Characters
my_turquoise2 = "#72a59e" # URL
my_green      = "#99be70" # Strings, Inherited Class, Markup Code, Diff Inserted
my_brown      = "#cfba8b" # Member variables, Quotes
my_yellow1    = "#FAD566" # Functions, Methods, Attribute IDs, Headings
my_yellow2    = "#ffff9f" # Debug, Info
my_red        = "#F05E48" # Keywords, Storage, Selector, Diff Changed
