attribute = "blue"
keyword = "blue"
"keyword.directive" = "red" # -- preprocessor comments (#if in C)
namespace = "peach"
punctuation = "white"
"punctuation.delimiter" = "blue"
operator = "blue"
special = "peach"
"variable.other.member" = "green"
variable = "peach"
"variable.parameter" = { fg = "pink" }
"variable.builtin" = "green"
type = "blue"
"type.builtin" = "white"
constructor = "blue"
function = "red"
"function.macro" = "blue"
"function.builtin" = "blue"
tag = "peach"
comment = "gray_1"
constant = "white"
"constant.builtin" = "green"
string = "green"
"constant.numeric" = "blue"
"constant.character.escape" = "peach"
# used for lifetimes
label = "peach"

"markup.heading" = "mauve"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "gray_2", modifiers = ["underlined"] }
"markup.link.text" = "peach"
"markup.raw" = "peach"

"diff.plus" = "#35bf86"
"diff.minus" = "#f22c86"
"diff.delta" = "#6F44F0"

"ui.background" = { bg = "black_2" }
"ui.linenr" = { fg = "gray_0" }
"ui.linenr.selected" = { fg = "mauve" }
"ui.statusline" = { fg = "black_2", bg = "blue" }
"ui.statusline.inactive" = { fg = "pink", bg = "gray_1" }
"ui.popup" = { bg = "black_1" }
"ui.window" = { fg = "maroon" }
"ui.help" = { bg = "#7958DC", fg = "#171452" }

"ui.text" = { fg = "pink" }
"ui.text.focus" = { fg = "white" }
"ui.virtual.whitespace" = { fg = "gray_0" }

"ui.selection" = { bg = "#540099" }
"ui.selection.primary" = { bg = "#540099" }
"ui.cursor.select" = { bg = "lavender" }
"ui.cursor.insert" = { bg = "white" }
"ui.cursor.match" = { fg = "#212121", bg = "#6C6999" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.highlight" = { bg = "maroon" }

"ui.menu.selected" = { fg = "gray_1", bg = "white" }

diagnostic = { modifiers = ["underlined"] }

warning = "peach"
error = "maroon"
info = "blue"
hint = "lavender"

[palette]
flamingo = "#F2CDCD"
mauve = "#DDB6F2"
pink = "#F5C2E7"
maroon = "#E8A2AF"
red = "#F28FAD"
peach = "#F8BD96"
yellow = "#FAE3B0"
green = "#ABE9B3"
teal = "#B5E8E0"
blue = "#96CDFB"
sky = "#89DCEB"

black_0 = "#161320"
black_1 = "#1A1826"
black_2 = "#1E1E2E"
black_3 = "#302D41"
black_4 = "#575268"
gray_0 = "#6E6C7E"
gray_1 = "#988BA2"
gray_2 = "#C3BAC6"
white = "#D9E0EE"
lavender = "#C9CBFF"
rosewater = "#F5E0DC"
