# Ported by Yevgnen.

"comment" = { fg = "firebrick" }
"constant" = { fg = "dark_cyan" }
"constant.builtin" = { fg = "dark_slate_blue" }
"function" = { fg = "blue1" }
"function.call" = { fg = "blue1" }
"function.macro" = { fg = "dark_slate_blue" }
"function.builtin" = { fg = "dark_slate_blue" }
"function.special" = { fg = "dark_slate_blue" }
"keyword" = { fg = "purple" }
"operator" = { fg = "purple" }
"punctuation" = { fg = "black" }
"string" = { fg = "violetred4" }
"string.special" = { fg = "violetred4", modifiers = ["bold"] }
"type" = { fg = "forest_green" }
"type.builtin" = { fg = "dark_slate_blue" }
"constructor" = { fg = "forest_green" }
"variable" = { fg = "sienna" }
"variable.builtin" = { fg = "dark_slate_blue" }
"variable.parameter" = { fg = "sienna" }
"tag" = { fg = "blue1" }
"label" = { fg = "dark_slate_blue" }
"attribute" = { fg = "dark_slate_blue" }
"namespace" = { fg = "dark_cyan" }
"module" = { fg = "dark_cyan" }
"special" = { fg = "blue1" }

"markup.heading" = { fg = "gold", modifiers = ["bold"] }
"markup.heading.marker" = { fg = "gray60" }
"markup.heading.1" = { fg = "blue1" }
"markup.heading.2" = { fg = "sienna" }
"markup.heading.3" = { fg = "purple" }
"markup.heading.4" = { fg = "firebrick" }
"markup.heading.5" = { fg = "forest_green" }
"markup.heading.6" = { fg = "dark_cyan" }
"markup.list" = { fg = "black" }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "royalblue3", modifiers = ["underlined"] }
"markup.link.text" = { fg = "royalblue3" }
"markup.quote" = { fg = "gray60" }
"markup.raw.inline" = { fg = "dark_cyan" }
"markup.raw.block" = { fg = "dark_cyan" }

"ui.background" = { fg = "black", bg = "white" }
"ui.background.separator" = { fg = "black", bg = "white" }
"ui.cursor" = { fg = "white", bg = "gray70" }
"ui.cursor.primary" = { fg = "white", bg = "black" }
"ui.cursor.match" = { fg = "black", bg = "turquoise" }
"ui.cursor.select" = { fg = "white", bg = "black" }
"ui.cursor.insert" = { fg = "red", bg = "black" }
"ui.linenr" = { fg = "gray60" }
"ui.linenr.selected" = { fg = "gray80" }
"ui.statusline" = { fg = "black", bg = "gray75" }
"ui.statusline.inactive" = { fg = "gray20", bg = "gray90" }
"ui.bufferline" = { fg = "gray36", bg = "gray90", modifiers = ["underlined"] }
"ui.bufferline.active" = { fg = "gray0", bg = "gray99" }
"ui.bufferline.background" = { bg = "gray75" }
"ui.popup" = { fg = "black", bg = "gray97" }
"ui.popup.info" = { fg = "black", bg = "gray97" }
"ui.window" = { fg = "black" }
"ui.help" = { fg = "dark_red", bg = "cornsilk" }
"ui.text" = { fg = "black" }
"ui.text.focus" = { fg = "black", bg = "darkseagreen2" }
"ui.menu" = { fg = "black", bg = "cornsilk" }
"ui.menu.selected" = { fg = "dark_red", bg = "light_blue" }
"ui.selection" = { bg = "lightgoldenrod1" }
"ui.selection.primary" = { bg = "lightgoldenrod2" }
# Malformed ANSI: highlight. See 'https://github.com/helix-editor/helix/issues/5709'
# "ui.virtual.whitespace" = "highlight"
"ui.virtual.ruler" = { bg = "gray95" }
"ui.virtual.inlay-hint" = { fg = "gray75" }
"ui.cursorline.primary" = { bg = "darkseagreen2" }
"ui.cursorline.secondary" = { bg = "darkseagreen2" }

"diff.plus" = { fg = "green3" }
"diff.delta" = { fg = "orange2" }
"diff.minus" = { fg = "red2" }

"error" = { fg = "red1" }
"warning" = { fg = "dark_orange" }
"info" = { fg = "forest_green" }
"hint" = { fg = "dark_cyan" }

"diagnostic.error" = { underline = { color = "red1", style = "curl" } }
"diagnostic.warning" = { underline = { color = "dark_orange", style = "curl" } }
"diagnostic.info" = { underline = { color = "forest_green", style = "curl" } }
"diagnostic.hint" = { underline = { color = "dark_cyan", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

[palette]
black = "#000000"
dim_gray = "#696969"
dark_gray = "#a9a9a9"
gray = "#bebebe"
light_gray = "#d3d3d3"
gainsboro = "#dcdcdc"
white_smoke = "#f5f5f5"
white = "#ffffff"
red = "#ff0000"
orange_red = "#ff4500"
dark_orange = "#ff8c00"
orange = "#ffa500"
gold = "#ffd700"
yellow = "#ffff00"
chartreuse = "#7fff00"
lawn_green = "#7cfc00"
green = "#00ff00"
spring_green = "#00ff7f"
medium_spring_green = "#00fa9a"
cyan = "#00ffff"
deep_sky_blue = "#00bfff"
blue = "#0000ff"
medium_blue = "#0000cd"
dark_violet = "#9400d3"
dark_magenta = "#8b008b"
magenta = "#ff00ff"
dark_red = "#8b0000"
brown = "#a52a2a"
firebrick = "#b22222"
indian_red = "#cd5c5c"
light_coral = "#f08080"
salmon = "#fa8072"
light_salmon = "#ffa07a"
tomato = "#ff6347"
coral = "#ff7f50"
dark_salmon = "#e9967a"
rosy_brown = "#bc8f8f"
sienna = "#a0522d"
saddle_brown = "#8b4513"
chocolate = "#d2691e"
peru = "#cd853f"
sandy_brown = "#f4a460"
burlywood = "#deb887"
tan = "#d2b48c"
navajo_white = "#ffdead"
wheat = "#f5deb3"
dark_goldenrod = "#b8860b"
goldenrod = "#daa520"
light_goldenrod = "#eedd82"
pale_goldenrod = "#eee8aa"
cornsilk = "#fff8dc"
dark_khaki = "#bdb76b"
khaki = "#f0e68c"
lemon_chiffon = "#fffacd"
dark_olive_green = "#556b2f"
olive_drab = "#6b8e23"
yellow_green = "#9acd32"
green_yellow = "#adff2f"
light_green = "#90ee90"
forest_green = "#228b22"
dark_green = "#006400"
lime_green = "#32cd32"
pale_green = "#98fb98"
dark_sea_green = "#8fbc8f"
sea_green = "#2e8b57"
medium_sea_green = "#3cb371"
light_sea_green = "#20b2aa"
medium_aquamarine = "#66cdaa"
aquamarine = "#7fffd4"
dark_cyan = "#008b8b"
dark_turquoise = "#00ced1"
medium_turquoise = "#48d1cc"
turquoise = "#40e0d0"
pale_turquoise = "#afeeee"
powder_blue = "#b0e0e6"
light_blue = "#add8e6"
sky_blue = "#87ceeb"
light_sky_blue = "#87cefa"
cadet_blue = "#5f9ea0"
steel_blue = "#4682b4"
dark_slate_gray = "#2f4f4f"
slate_gray = "#708090"
light_slate_gray = "#778899"
royal_blue = "#4169e1"
dodger_blue = "#1e90ff"
cornflower_blue = "#6495ed"
light_steel_blue = "#b0c4de"
dark_blue = "#00008b"
navy = "#000080"
midnight_blue = "#191970"
dark_slate_blue = "#483d8b"
slate_blue = "#6a5acd"
medium_slate_blue = "#7b68ee"
light_slate_blue = "#8470ff"
medium_purple = "#9370db"
blue_violet = "#8a2be2"
purple = "#a020f0"
dark_orchid = "#9932cc"
medium_orchid = "#ba55d3"
orchid = "#da70d6"
thistle = "#d8bfd8"
plum = "#dda0dd"
violet = "#ee82ee"
medium_violet_red = "#c71585"
violet_red = "#d02090"
pale_violet_red = "#db7093"
maroon = "#b03060"
deep_pink = "#ff1493"
hot_pink = "#ff69b4"
pink = "#ffc0cb"
light_pink = "#ffb6c1"
snow = "#fffafa"
misty_rose = "#ffe4e1"
seashell = "#fff5ee"
peach_puff = "#ffdab9"
linen = "#faf0e6"
antique_white = "#faebd7"
bisque = "#ffe4c4"
papaya_whip = "#ffefd5"
moccasin = "#ffe4b5"
blanched_almond = "#ffebcd"
old_lace = "#fdf5e6"
floral_white = "#fffaf0"
beige = "#f5f5dc"
light_yellow = "#ffffe0"
light_goldenrod_yellow = "#fafad2"
ivory = "#fffff0"
honeydew = "#f0fff0"
mint_cream = "#f5fffa"
light_cyan = "#e0ffff"
azure = "#f0ffff"
alice_blue = "#f0f8ff"
lavender = "#e6e6fa"
ghost_white = "#f8f8ff"
lavender_blush = "#fff0f5"
red4 = "#8b0000"
red3 = "#cd0000"
red2 = "#ee0000"
red1 = "#ff0000"
orangered4 = "#8b2500"
orangered3 = "#cd3700"
orangered2 = "#ee4000"
orangered1 = "#ff4500"
darkorange4 = "#8b4500"
darkorange3 = "#cd6600"
darkorange2 = "#ee7600"
darkorange1 = "#ff7f00"
orange4 = "#8b5a00"
orange3 = "#cd8500"
orange2 = "#ee9a00"
orange1 = "#ffa500"
gold4 = "#8b7500"
gold3 = "#cdad00"
gold2 = "#eec900"
gold1 = "#ffd700"
yellow4 = "#8b8b00"
yellow3 = "#cdcd00"
yellow2 = "#eeee00"
yellow1 = "#ffff00"
chartreuse4 = "#458b00"
chartreuse3 = "#66cd00"
chartreuse2 = "#76ee00"
chartreuse1 = "#7fff00"
green4 = "#008b00"
green3 = "#00cd00"
green2 = "#00ee00"
green1 = "#00ff00"
springgreen4 = "#008b45"
springgreen3 = "#00cd66"
springgreen2 = "#00ee76"
springgreen1 = "#00ff7f"
cyan4 = "#008b8b"
cyan3 = "#00cdcd"
cyan2 = "#00eeee"
cyan1 = "#00ffff"
turquoise4 = "#00868b"
turquoise3 = "#00c5cd"
turquoise2 = "#00e5ee"
turquoise1 = "#00f5ff"
deepskyblue4 = "#00688b"
deepskyblue3 = "#009acd"
deepskyblue2 = "#00b2ee"
deepskyblue1 = "#00bfff"
blue4 = "#00008b"
blue3 = "#0000cd"
blue2 = "#0000ee"
blue1 = "#0000ff"
magenta4 = "#8b008b"
magenta3 = "#cd00cd"
magenta2 = "#ee00ee"
magenta1 = "#ff00ff"
brown4 = "#8b2323"
brown3 = "#cd3333"
brown2 = "#ee3b3b"
brown1 = "#ff4040"
firebrick4 = "#8b1a1a"
firebrick3 = "#cd2626"
firebrick2 = "#ee2c2c"
firebrick1 = "#ff3030"
indianred4 = "#8b3a3a"
indianred3 = "#cd5555"
indianred2 = "#ee6363"
indianred1 = "#ff6a6a"
rosybrown4 = "#8b6969"
rosybrown3 = "#cd9b9b"
rosybrown2 = "#eeb4b4"
rosybrown1 = "#ffc1c1"
snow4 = "#8b8989"
snow3 = "#cdc9c9"
snow2 = "#eee9e9"
snow1 = "#fffafa"
mistyrose4 = "#8b7d7b"
mistyrose3 = "#cdb7b5"
mistyrose2 = "#eed5d2"
mistyrose1 = "#ffe4e1"
tomato4 = "#8b3626"
tomato3 = "#cd4f39"
tomato2 = "#ee5c42"
tomato1 = "#ff6347"
coral4 = "#8b3e2f"
coral3 = "#cd5b45"
coral2 = "#ee6a50"
coral1 = "#ff7256"
salmon4 = "#8b4c39"
salmon3 = "#cd7054"
salmon2 = "#ee8262"
salmon1 = "#ff8c69"
lightsalmon4 = "#8b5742"
lightsalmon3 = "#cd8162"
lightsalmon2 = "#ee9572"
lightsalmon1 = "#ffa07a"
sienna4 = "#8b4726"
sienna3 = "#cd6839"
sienna2 = "#ee7942"
sienna1 = "#ff8247"
chocolate4 = "#8b4513"
chocolate3 = "#cd661d"
chocolate2 = "#ee7621"
chocolate1 = "#ff7f24"
seashell4 = "#8b8682"
seashell3 = "#cdc5bf"
seashell2 = "#eee5de"
seashell1 = "#fff5ee"
peachpuff4 = "#8b7765"
peachpuff3 = "#cdaf95"
peachpuff2 = "#eecbad"
peachpuff1 = "#ffdab9"
tan4 = "#8b5a2b"
tan3 = "#cd853f"
tan2 = "#ee9a49"
tan1 = "#ffa54f"
bisque4 = "#8b7d6b"
bisque3 = "#cdb79e"
bisque2 = "#eed5b7"
bisque1 = "#ffe4c4"
antiquewhite4 = "#8b8378"
antiquewhite3 = "#cdc0b0"
antiquewhite2 = "#eedfcc"
antiquewhite1 = "#ffefdb"
burlywood4 = "#8b7355"
burlywood3 = "#cdaa7d"
burlywood2 = "#eec591"
burlywood1 = "#ffd39b"
navajowhite4 = "#8b795e"
navajowhite3 = "#cdb38b"
navajowhite2 = "#eecfa1"
navajowhite1 = "#ffdead"
wheat4 = "#8b7e66"
wheat3 = "#cdba96"
wheat2 = "#eed8ae"
wheat1 = "#ffe7ba"
darkgoldenrod4 = "#8b6508"
darkgoldenrod3 = "#cd950c"
darkgoldenrod2 = "#eead0e"
darkgoldenrod1 = "#ffb90f"
goldenrod4 = "#8b6914"
goldenrod3 = "#cd9b1d"
goldenrod2 = "#eeb422"
goldenrod1 = "#ffc125"
cornsilk4 = "#8b8878"
cornsilk3 = "#cdc8b1"
cornsilk2 = "#eee8cd"
cornsilk1 = "#fff8dc"
lightgoldenrod4 = "#8b814c"
lightgoldenrod3 = "#cdbe70"
lightgoldenrod2 = "#eedc82"
lightgoldenrod1 = "#ffec8b"
lemonchiffon4 = "#8b8970"
lemonchiffon3 = "#cdc9a5"
lemonchiffon2 = "#eee9bf"
lemonchiffon1 = "#fffacd"
khaki4 = "#8b864e"
khaki3 = "#cdc673"
khaki2 = "#eee685"
khaki1 = "#fff68f"
lightyellow4 = "#8b8b7a"
lightyellow3 = "#cdcdb4"
lightyellow2 = "#eeeed1"
lightyellow1 = "#ffffe0"
ivory4 = "#8b8b83"
ivory3 = "#cdcdc1"
ivory2 = "#eeeee0"
ivory1 = "#fffff0"
olivedrab4 = "#698b22"
olivedrab3 = "#9acd32"
olivedrab2 = "#b3ee3a"
olivedrab1 = "#c0ff3e"
darkolivegreen4 = "#6e8b3d"
darkolivegreen3 = "#a2cd5a"
darkolivegreen2 = "#bcee68"
darkolivegreen1 = "#caff70"
palegreen4 = "#548b54"
palegreen3 = "#7ccd7c"
palegreen2 = "#90ee90"
palegreen1 = "#9aff9a"
darkseagreen4 = "#698b69"
darkseagreen3 = "#9bcd9b"
darkseagreen2 = "#b4eeb4"
darkseagreen1 = "#c1ffc1"
honeydew4 = "#838b83"
honeydew3 = "#c1cdc1"
honeydew2 = "#e0eee0"
honeydew1 = "#f0fff0"
seagreen4 = "#2e8b57"
seagreen3 = "#43cd80"
seagreen2 = "#4eee94"
seagreen1 = "#54ff9f"
aquamarine4 = "#458b74"
aquamarine3 = "#66cdaa"
aquamarine2 = "#76eec6"
aquamarine1 = "#7fffd4"
darkslategray4 = "#528b8b"
darkslategray3 = "#79cdcd"
darkslategray2 = "#8deeee"
darkslategray1 = "#97ffff"
paleturquoise4 = "#668b8b"
paleturquoise3 = "#96cdcd"
paleturquoise2 = "#aeeeee"
paleturquoise1 = "#bbffff"
lightcyan4 = "#7a8b8b"
lightcyan3 = "#b4cdcd"
lightcyan2 = "#d1eeee"
lightcyan1 = "#e0ffff"
azure4 = "#838b8b"
azure3 = "#c1cdcd"
azure2 = "#e0eeee"
azure1 = "#f0ffff"
cadetblue4 = "#53868b"
cadetblue3 = "#7ac5cd"
cadetblue2 = "#8ee5ee"
cadetblue1 = "#98f5ff"
lightblue4 = "#68838b"
lightblue3 = "#9ac0cd"
lightblue2 = "#b2dfee"
lightblue1 = "#bfefff"
lightskyblue4 = "#607b8b"
lightskyblue3 = "#8db6cd"
lightskyblue2 = "#a4d3ee"
lightskyblue1 = "#b0e2ff"
skyblue4 = "#4a708b"
skyblue3 = "#6ca6cd"
skyblue2 = "#7ec0ee"
skyblue1 = "#87ceff"
steelblue4 = "#36648b"
steelblue3 = "#4f94cd"
steelblue2 = "#5cacee"
steelblue1 = "#63b8ff"
dodgerblue4 = "#104e8b"
dodgerblue3 = "#1874cd"
dodgerblue2 = "#1c86ee"
dodgerblue1 = "#1e90ff"
slategray4 = "#6c7b8b"
slategray3 = "#9fb6cd"
slategray2 = "#b9d3ee"
slategray1 = "#c6e2ff"
lightsteelblue4 = "#6e7b8b"
lightsteelblue3 = "#a2b5cd"
lightsteelblue2 = "#bcd2ee"
lightsteelblue1 = "#cae1ff"
royalblue4 = "#27408b"
royalblue3 = "#3a5fcd"
royalblue2 = "#436eee"
royalblue1 = "#4876ff"
slateblue4 = "#473c8b"
slateblue3 = "#6959cd"
slateblue2 = "#7a67ee"
slateblue1 = "#836fff"
mediumpurple4 = "#5d478b"
mediumpurple3 = "#8968cd"
mediumpurple2 = "#9f79ee"
mediumpurple1 = "#ab82ff"
purple4 = "#551a8b"
purple3 = "#7d26cd"
purple2 = "#912cee"
purple1 = "#9b30ff"
darkorchid4 = "#68228b"
darkorchid3 = "#9a32cd"
darkorchid2 = "#b23aee"
darkorchid1 = "#bf3eff"
mediumorchid4 = "#7a378b"
mediumorchid3 = "#b452cd"
mediumorchid2 = "#d15fee"
mediumorchid1 = "#e066ff"
thistle4 = "#8b7b8b"
thistle3 = "#cdb5cd"
thistle2 = "#eed2ee"
thistle1 = "#ffe1ff"
plum4 = "#8b668b"
plum3 = "#cd96cd"
plum2 = "#eeaeee"
plum1 = "#ffbbff"
orchid4 = "#8b4789"
orchid3 = "#cd69c9"
orchid2 = "#ee7ae9"
orchid1 = "#ff83fa"
maroon4 = "#8b1c62"
maroon3 = "#cd2990"
maroon2 = "#ee30a7"
maroon1 = "#ff34b3"
deeppink4 = "#8b0a50"
deeppink3 = "#cd1076"
deeppink2 = "#ee1289"
deeppink1 = "#ff1493"
hotpink4 = "#8b3a62"
hotpink3 = "#cd6090"
hotpink2 = "#ee6aa7"
hotpink1 = "#ff6eb4"
violetred4 = "#8b2252"
violetred3 = "#cd3278"
violetred2 = "#ee3a8c"
violetred1 = "#ff3e96"
lavenderblush4 = "#8b8386"
lavenderblush3 = "#cdc1c5"
lavenderblush2 = "#eee0e5"
lavenderblush1 = "#fff0f5"
palevioletred4 = "#8b475d"
palevioletred3 = "#cd6889"
palevioletred2 = "#ee799f"
palevioletred1 = "#ff82ab"
pink4 = "#8b636c"
pink3 = "#cd919e"
pink2 = "#eea9b8"
pink1 = "#ffb5c5"
lightpink4 = "#8b5f65"
lightpink3 = "#cd8c95"
lightpink2 = "#eea2ad"
lightpink1 = "#ffaeb9"
gray0 = "#000000"
gray1 = "#030303"
gray2 = "#050505"
gray3 = "#080808"
gray4 = "#0a0a0a"
gray5 = "#0d0d0d"
gray6 = "#0f0f0f"
gray7 = "#121212"
gray8 = "#141414"
gray9 = "#171717"
gray10 = "#1a1a1a"
gray11 = "#1c1c1c"
gray12 = "#1f1f1f"
gray13 = "#212121"
gray14 = "#242424"
gray15 = "#262626"
gray16 = "#292929"
gray17 = "#2b2b2b"
gray18 = "#2e2e2e"
gray19 = "#303030"
gray20 = "#333333"
gray21 = "#363636"
gray22 = "#383838"
gray23 = "#3b3b3b"
gray24 = "#3d3d3d"
gray25 = "#404040"
gray26 = "#424242"
gray27 = "#454545"
gray28 = "#474747"
gray29 = "#4a4a4a"
gray30 = "#4d4d4d"
gray31 = "#4f4f4f"
gray32 = "#525252"
gray33 = "#545454"
gray34 = "#575757"
gray35 = "#595959"
gray36 = "#5c5c5c"
gray37 = "#5e5e5e"
gray38 = "#616161"
gray39 = "#636363"
gray40 = "#666666"
gray41 = "#696969"
gray42 = "#6b6b6b"
gray43 = "#6e6e6e"
gray44 = "#707070"
gray45 = "#737373"
gray46 = "#757575"
gray47 = "#787878"
gray48 = "#7a7a7a"
gray49 = "#7d7d7d"
gray50 = "#7f7f7f"
gray51 = "#828282"
gray52 = "#858585"
gray53 = "#878787"
gray54 = "#8a8a8a"
gray55 = "#8c8c8c"
gray56 = "#8f8f8f"
gray57 = "#919191"
gray58 = "#949494"
gray59 = "#969696"
gray60 = "#999999"
gray61 = "#9c9c9c"
gray62 = "#9e9e9e"
gray63 = "#a1a1a1"
gray64 = "#a3a3a3"
gray65 = "#a6a6a6"
gray66 = "#a8a8a8"
gray67 = "#ababab"
gray68 = "#adadad"
gray69 = "#b0b0b0"
gray70 = "#b3b3b3"
gray71 = "#b5b5b5"
gray72 = "#b8b8b8"
gray73 = "#bababa"
gray74 = "#bdbdbd"
gray75 = "#bfbfbf"
gray76 = "#c2c2c2"
gray77 = "#c4c4c4"
gray78 = "#c7c7c7"
gray79 = "#c9c9c9"
gray80 = "#cccccc"
gray81 = "#cfcfcf"
gray82 = "#d1d1d1"
gray83 = "#d4d4d4"
gray84 = "#d6d6d6"
gray85 = "#d9d9d9"
gray86 = "#dbdbdb"
gray87 = "#dedede"
gray88 = "#e0e0e0"
gray89 = "#e3e3e3"
gray90 = "#e5e5e5"
gray91 = "#e8e8e8"
gray92 = "#ebebeb"
gray93 = "#ededed"
gray94 = "#f0f0f0"
gray95 = "#f2f2f2"
gray96 = "#f5f5f5"
gray97 = "#f7f7f7"
gray98 = "#fafafa"
gray99 = "#fcfcfc"
gray100 = "#ffffff"
