# Author : Sven-Hendrik Haase <svenstaro@gmail.com>
# Author : Jakub Bartodziej <kubabartodziej@gmail.com>
# The theme uses the gruvbox dark palette with hard contrast: github.com/morhetz/gruvbox

inherits = "gruvbox"

"ui.cursor.primary" = { modifiers = ["reversed"] }
"ui.cursor.match" = { bg = "bg2" }

"diagnostic.error" = { underline = { color = "red0", style = "curl"} }

[palette]
bg0 = "#1d2021" # main background
