inherits = "monokai"

"keyword.control.import" = { fg = "cyan", modifiers = ["italic"] }
"keyword.function" = { fg = "cyan", modifiers = ["italic"] }
"keyword.storage.type" = { fg = "cyan", modifiers = ["italic"] }

"namespace" = { fg = "text" }

"type" = { fg = "type", modifiers = ["bold"] }

# Malformed ANSI: light-black, purple. See 'https://github.com/helix-editor/helix/issues/5709'
# "ui.statusline.normal" = { fg = "light-black", bg = "cyan" }
"ui.statusline.normal" = { bg = "cyan" }
# "ui.statusline.insert" = { fg = "light-black", bg = "green" }
"ui.statusline.insert" = { bg = "green" }
# "ui.statusline.select" = { fg = "light-black", bg = "purple" }

"ui.virtual.jump-label" = { fg = "cyan", modifiers = ["bold"] }

[palette]
cyan = "#66D9EF"
type = "#66D9EF"
