# Author : RayGervais<raygervais@hotmail.ca>

"ui.linenr.selected" = { fg = "nord4" }
"ui.text.focus" = { fg = "nord8", modifiers= ["bold"] }
"ui.menu.selected" = { fg = "nord8", bg = "nord2" }
"ui.virtual" = "gray"

"info" = "nord8"
"hint" = "nord8"

# Polar Night
# nord0 - background color
"ui.background" = { bg = "nord0" }
"ui.statusline.inactive" = { fg = "nord8", bg = "nord1" }


# nord1 - status bars, panels, modals, autocompletion
"ui.statusline" = { fg = "nord4", bg = "#4c566a" }
"ui.popup" = { bg = "#232d38" }
"ui.window" = { bg = "#232d38" }
"ui.help" = { bg = "#232d38", fg = "nord4" }

# nord2 - active line, highlighting
"ui.selection" = { bg = "nord2" }
"ui.cursor.match" = { bg = "nord2" }

# nord3 - comments, nord3 based lighter color
# relative: https://github.com/arcticicestudio/nord/issues/94
"comment" = { fg = "gray", modifiers = ["italic"] }
"ui.linenr" = { fg = "gray" }

# Snow Storm
# nord4 - cursor, variables, constants, attributes, fields
"ui.cursor.primary" = { fg = "nord4", modifiers = ["reversed"] }
"attribute" = "nord4"
"variable"  = "nord4"
"constant"  = "nord4"
"variable.builtin" = "nord4"
"constant.builtin" = "nord4"
"namespace" = "nord4"

# nord5 - suble UI text

# nord6 - base text, punctuation
"ui.text" = { fg = "nord6" }
"punctuation" = "nord6"

# Frost
# nord7 - classes, types, primitives
"type" = "nord7"
"type.builtin" = { fg = "nord7"}
"label" = "nord7"

# nord8 - declaration, methods, routines
"constructor" = "nord8"
"function" = "nord8"
"function.macro" = { fg = "nord8" }
"function.builtin" = { fg = "nord8" }

# nord9 - operator, tags, units, punctuations
"punctuation.delimiter" = "nord9"
"operator" = { fg = "nord9" }
"variable.other.member" = "nord9"

# nord10 - keywords, special
"keyword" = { fg = "nord10" }
"keyword.directive" = "nord10"
"variable.parameter" = "nord10"

# Aurora
# nord11 - error
"error" = "nord11"

# nord12 - annotations, decorators
"special" = "nord12"
"module" = "nord12"

# nord13 - warnings, escape characters, regex
"warning" = "nord13"
"constant.character.escape" = { fg = "nord13" }

# nord14 - strings
"string" = "nord14"

# nord15 - integer, floating point
"constant.numeric" = "nord15"

# TODO markup
"markup.heading" = "blue"
"markup.list" = "red"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "magenta", modifiers = ["italic"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.quote" = "cyan"
"markup.raw" = "green"

# vcs
"diff.plus" = "nord14"
"diff.delta" = "nord12"
"diff.minus" = "nord11"

[palette]
nord0 = "#2e3440"
nord1 = "#3b4252"
nord2 = "#434c5e"
nord4 = "#d8dee9"
nord6 = "#eceff4"
nord7 = "#8fbcbb"
nord8 = "#88c0d0"
nord9 = "#81a1c1"
nord10 = "#5e81ac"
nord11 = "#bf616a"
nord12 = "#d08770"
nord13 = "#ebcb8b"
nord14 = "#a3be8c"
nord15 = "#b48ead"
gray = "#616e88"
