# Serika (Dark)
# Author: VuiMuich

# Original Author:
# URL: https://github.com/arturoalviar/serika-syntax
# Author: arturoalviar
# License: MIT License

"escape" = "orange"
"type" = "yellow"
"constant" = "purple"
"number" = "purple"
"string" = "fg"
"comment" = "grey2"
"variable" = "yellow"
"variable.builtin" = "blue"
"variable.parameter" = "yellow"
"variable.property" = "yellow"
"label" = "aqua"
"punctuation" = "grey0"
"punctuation.delimiter" = "bg4"
"punctuation.bracket" = "fg"
"keyword" = "red"
"operator" = "grey0"
"function" = "green"
"function.builtin" = "blue"
"function.macro" = "aqua"
"tag" = "yellow"
"namespace" = "fg"
"attribute" = "aqua"
"constructor" = "yellow"
"module" = "blue"
"special" = "orange"

"ui.background" = { bg = "bg0" }
"ui.cursor" = { fg = "bg0", bg = "fg" }
"ui.cursor.match" = { fg = "grey0", bg = "grey2" }
"ui.cursor.insert" = { fg = "bg0", bg = "bg_yellow" }
"ui.cursor.select" = { fg = "bg0", bg = "bg_yellow" }
"ui.linenr" = "yellow"
"ui.linenr.selected" = { fg = "fg", modifiers = ["bold", "underlined"] }
"ui.cursorline" = { fg = "grey1", bg = "bg2" }
"ui.statusline" = { fg = "grey1", bg = "bg2" }
"ui.statusline.inactive" = { fg = "grey2", bg = "bg1" }
"ui.popup" = { fg = "grey2", bg = "bg1" }
"ui.window" = { fg = "grey2", bg = "bg1" }
"ui.help" = { fg = "fg", bg = "bg1" }
"ui.text" = "fg"
"ui.text.focus" = "yellow"
"ui.menu" = { fg = "fg", bg = "bg2" }
"ui.menu.selected" = { fg = "bg0", bg = "bg_yellow" }
"ui.selection" = { bg = "bg3" }
"ui.virtual.whitespace" = "bg2"
"ui.virtual.ruler" = { bg = "grey2" } 
"ui.virtual.inlay-hint" = { fg = "grey2", modifiers = ["italic"] }

"hint" = "blue"
"info" = "aqua"
"warning" = "yellow"
"error" = "nasty-red"

"diagnostic.hint" = { underline = { style = "curl", color = "blue" } }
"diagnostic.info" = { underline = { style = "curl", color = "aqua" } }
"diagnostic.warning" = { underline = { style = "curl", color = "yellow" } }
"diagnostic.error" = { underline = { style = "curl", color = "nasty-red" } }

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "orange" }
"diff.minus" = { fg = "nasty-red" }

"markup.heading" = { fg = "purple", modifiers = ["bold"] }
"markup.list" = "cyan"
"markup.bold" = { fg = "orange", modifiers = ["bold"] }
"markup.italic" = { fg = "yellow", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = "cyan"
"markup.link.text" = "pink"
"markup.quote" = { fg = "yellow", modifiers = ["italic"] }
"markup.raw" = { fg = "fg" }

[palette]

bg0 = "#323437"
bg1 = "#494c50"
bg2 = "#55585e"
bg3 = "#61656b"
bg4 = "#6d7278"
bg5 = "#797e86"
bg_visual = "#646669"
bg_red = "#7e2a33"
bg_green = "#86b365"
bg_blue = "#6a89af"
bg_yellow = "#e2b714"

fg = "#d1d0c5"
red = "#f9ebed"
nasty-red = "#ca4754"
dark-red = "#7e2a33"
orange = "#dd8a3c"
yellow = "#e2b714"
green = "#e5eae1"
aqua = "#b9c2c6"
blue = "#bdcadb"
purple = "#d0c4d4"
grey0 = "#aaaeb3"
grey1 = "#e1e1e3"
grey2 = "#646669"
pink = "#e06c75"
