# A unofficial port of VIM's zenburn theme: https://github.com/jnurmine/Zenburn/

"ui.background" = { bg = "bg" }
"ui.menu" = { fg = "#9f9f9f", bg = "uibg" }
"ui.menu.selected" = { fg = "#d0d0a0", bg = "#242424", modifiers = ["bold"] }
"ui.linenr" = { fg = "#9fafaf", bg = "#262626"}
"ui.linenr.selected" = { modifiers = ["bold"]}
"ui.popup" = { bg = "uibg" }
"ui.selection" = { bg = "#304a3d" }
"ui.selection.primary" = { bg = "#2f2f2f" }
"comment" = { fg = "comment" }
"ui.virtual.inlay-hint" = { fg = "#9f9f9f" }
"comment.block.documentation" = { fg = "black", modifiers = ["bold"] }
"ui.statusline" = { bg = "statusbg", fg = "#ccdc90" }
"ui.statusline.inactive" = { fg = '#2e3330', bg = '#88b090' }
"ui.cursor" = { fg = "#000d18", bg = "#8faf9f", modifiers = ["bold"] }
"ui.text" = { fg = "normal"}
"operator" = { fg = "#f0efd0" , modifiers = []}
"variable" = "normal"
"variable.builtin" = {fg = "constant", modifiers = ["bold"]}
"constant.numeric" = "numeric"
"constant" = { fg = "constant", modifiers = ["bold"] }
"type" = { fg = "#dfdfbf", modifiers = ["bold"] }
"ui.cursor.match" = { fg = "#343434", bg = "#284f28", modifiers = ["bold"] }
"string"  = "#cc9393"
"variable.other.member" = "#efef8f"
"constant.character.escape" = { fg = "#dca3a3", modifiers = ["bold"]}
"function" = "#efef8f"
"function.macro" = { fg = "#ffcfaf", modifiers = ["bold"] }
"special" = "#cfbfaf"
"keyword" = { fg = "#f0dfaf", modifiers = ["bold"]}
"keyword.storage-class" = { fg = "#c3bf9f", modifiers = ["bold"]}
"label" = { fg = "#dfcfaf", modifiers = ["underlined"] }
"ui.help" = { fg = "white", bg = "black" }
"ui.virtual.ruler" = { bg = "#484848" }
"ui.virtual.whitespace" = { fg = "#5b605e", modifiers = ["bold"]}

"punctuation.delimiter" = "#8f8f8f"

"ui.virtual.indent-guide" = "#4f4f4f"

"diff.plus" = {fg = "#709080"}
"diff.delta" = {fg = "#464646"}
"diff.minus" = {fg = "#cc9393"}

"diagnostic" = {bg = "statusbg"}
"diagnostic.error" = { fg = "errorfg", bg = "errorbg"}
"ui.gutter" = { bg = "statusbg" }
"hint" = {fg = "numeric", bg = "statusbg"}
"warning" = "numeric"
"error" = "errorfg"

[palette]
comment = "#7f9f7f"
bg = "#3f3f3f"
uibg = "#2c2e2e"
constant = "#dca3a3"
normal = "#dcdccc"
todo = "#dfdfdf"
errorfg = "#e37170"
errorbg = "#3d3535"
statusbg = "#313633"
numeric = "#8cd0d3"