# Material Theme <https://material-theme.com/> for Helix Editor

inherits = "material_deep_ocean"

[palette]
bg = "#212121"
text = "#b0bec5"

gray = "#616161"
error = "#ff5370"

disabled = "#474747"

accent = "#ff9800"

active = "#323232"
highlight = "#3f3f3f"

comment = "#616161"

selection = "#404040"
