[package]
name = "helix-syntax"
version = "0.0.9"
authors = ["Bla≈æ Hrastnik <blaz@mxxn.io>"]
edition = "2018"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.19"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
cc = { version = "1",  features = ["parallel"] }
threadpool = { version = "1.0" }
