[package]
name = "helix-core"
version = "0.4.1"
authors = ["Bla≈æ Hrastnik <blaz@mxxn.io>"]
edition = "2018"
license = "MPL-2.0"
description = "Helix editor core editing primitives"
categories = ["editor"]
repository = "https://github.com/helix-editor/helix"
homepage = "https://helix-editor.com"
include = ["src/**/*", "README.md"]

[features]

[dependencies]
helix-syntax = { version = "0.4", path = "../helix-syntax" }
helix-dap = { version = "0.4", path = "../helix-dap" }

ropey = "1.3"
smallvec = "1.4"
tendril = "0.4.2"
unicode-segmentation = "1.8"
unicode-width = "0.1"
unicode-general-category = "0.4"
# slab = "0.4.2"
tree-sitter = "0.20"
once_cell = "1.8"
arc-swap = "1"
regex = "1"

serde = { version = "1.0", features = ["derive"] }
toml = "0.5"

similar = "2.0"

etcetera = "0.3"

[dev-dependencies]
quickcheck = { version = "1", default-features = false }
