[package]
name = "helix-core"
version = "0.6.0"
authors = ["Bla≈æ Hrastnik <blaz@mxxn.io>"]
edition = "2021"
license = "MPL-2.0"
description = "Helix editor core editing primitives"
categories = ["editor"]
repository = "https://github.com/helix-editor/helix"
homepage = "https://helix-editor.com"
include = ["src/**/*", "README.md"]

[features]
unicode-lines = ["ropey/unicode_lines"]
integration = []

[dependencies]
helix-loader = { version = "0.6", path = "../helix-loader" }

ropey = { version = "1.6.0", default-features = false, features = ["simd"] }
smallvec = "1.11"
smartstring = "1.0.1"
unicode-segmentation = "1.10"
unicode-width = "0.1"
unicode-general-category = "0.6"
# slab = "0.4.2"
slotmap = "1.0"
tree-sitter.workspace = true
once_cell = "1.18"
arc-swap = "1"
regex = "1"
bitflags = "2.4"
ahash = "0.8.3"
hashbrown = { version = "0.14.1", features = ["raw"] }
dunce = "1.0"

log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.7"

imara-diff = "0.1.0"

encoding_rs = "0.8"

chrono = { version = "0.4", default-features = false, features = ["alloc", "std"] }

etcetera = "0.8"
textwrap = "0.16.0"

nucleo.workspace = true
parking_lot = "0.12"

[dev-dependencies]
quickcheck = { version = "1", default-features = false }
indoc = "2.0.4"
