[package]
name = "helix-core"
version = "0.6.0"
authors = ["Bla≈æ Hrastnik <blaz@mxxn.io>"]
edition = "2021"
license = "MPL-2.0"
description = "Helix editor core editing primitives"
categories = ["editor"]
repository = "https://github.com/helix-editor/helix"
homepage = "https://helix-editor.com"
include = ["src/**/*", "README.md"]

[features]
unicode-lines = ["ropey/unicode_lines"]

[dependencies]
helix-loader = { version = "0.6", path = "../helix-loader" }

ropey = { version = "1.4", default-features = false }
smallvec = "1.8"
smartstring = "1.0.1"
unicode-segmentation = "1.9"
unicode-width = "0.1"
unicode-general-category = "0.5"
# slab = "0.4.2"
slotmap = "1.0"
tree-sitter = "0.20" # TODO: use tree-sitter-facade / web-tree-sitter-sys on wasm32
once_cell = "1.10"
arc-swap = "1"
regex = "1"

log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"

similar = "2.1"

encoding_rs = "0.8"

chrono = { version = "0.4", default-features = false, features = ["alloc", "std"] }

etcetera = "0.3"

[dev-dependencies]
quickcheck = { version = "1", default-features = false }
