name = "nerdfonts"

[diagnostic]
error = {icon = "îª‡"}
warning = {icon = "î©¬"}
info = {icon = "î©´"}
hint = {icon = "î¬²"}

[breakpoint]
verified = {icon = "â–²"}
unverified = {icon = "âŠš"} 

[diff]
added = {icon = "â–"}
deleted = {icon = "â–”"}
modified = {icon = "â–"}

[symbol-kind]
file = {icon = "î©»"}
module = {icon = "ï’‡"}
namespace = {icon = "ï’‡"}
package = {icon = "î¬©"}
class = {icon = "î­›"}
method = {icon = "îªŒ"}
property = {icon = "î­¥"}
field = {icon = "ïŠ’"}
constructor = {icon = "îˆ"}
enumeration = {icon = "ïƒŠ"}
interface = {icon = "ïƒ¨"}
variable = {icon = "ï”ª"}
function = {icon = "ó°Š•"}
constant = {icon = "î­"}
string = {icon = "î®"}
number = {icon = "ï“·"}
boolean = {icon = "îª"}
array = {icon = "îªŠ"}
object = {icon = "î¬©"}
key = {icon = "î¬‘"}
null = {icon = "ó°Ÿ¢"}
enum-member = {icon = "î­"}
structure = {icon = "î­›"}
event = {icon = "îª†"}
operator = {icon = "î­¤"}
type-parameter = {icon = "îª’"}

[ui]
file = {icon = "î©»"}
folder = {icon = "î—¿"}
folder_opened = {icon = "î—¾"}
git_branch = {icon = "îœ¥"}

[mime-type]
# This is heavily based on https://github.com/nvim-tree/nvim-web-devicons
".babelrc" = { icon = "ï¬¥", color = "#cbcb41" }
".bash_profile" = { icon = "î˜•", color = "#89e051" }
".bashrc" = { icon = "î˜•", color = "#89e051" }
".DS_Store" = { icon = "î˜•", color = "#41535b" }
".gitattributes" = { icon = "îœ‚", color = "#41535b" }
".gitconfig" = { icon = "î˜•", color = "#41535b" }
".gitignore" = { icon = "îœ‚", color = "#41535b" }
".gitlab-ci.yml" = { icon = "ïŠ–", color = "#e24329" }
".gitmodules" = { icon = "îœ‚", color = "#41535b" }
".gvimrc" = { icon = "î˜«", color = "#019833" }
".npmignore" = { icon = "îœ", color = "#E8274B" }
".npmrc" = { icon = "îœ", color = "#E8274B" }
".settings.json" = { icon = "îœŒ", color = "#854CC7" }
".vimrc" = { icon = "î˜«", color = "#019833" }
".zprofile" = { icon = "î˜•", color = "#89e051" }
".zshenv" = { icon = "î˜•", color = "#89e051" }
".zshrc" = { icon = "î˜•", color = "#89e051" }
"Brewfile" = { icon = "î‘", color = "#701516" }
"CMakeLists.txt" = { icon = "î˜•", color = "#6d8086" }
"COMMIT_EDITMSG" = { icon = "îœ‚", color = "#41535b" }
"COPYING" = { icon = "î˜Š", color = "#cbcb41" }
"COPYING.LESSER" = { icon = "î˜Š", color = "#cbcb41" }
"Dockerfile" = { icon = "î°", color = "#384d54" }
"Gemfile$" = { icon = "î‘", color = "#701516" }
"LICENSE" = { icon = "î˜Š", color = "#d0bf41" }
"R" = { icon = "ï³’", color = "#358a5b" }
"Rmd" = { icon = "î˜‰", color = "#519aba" }
"Vagrantfile$" = { icon = "ïŠ¸", color = "#1563FF" }
"_gvimrc" = { icon = "î˜«", color = "#019833" }
"_vimrc" = { icon = "î˜«", color = "#019833" }
"ai" = { icon = "î´", color = "#cbcb41" }
"awk" = { icon = "î•", color = "#4d5a5e" }
"bash" = { icon = "î•", color = "#89e051" }
"bat" = { icon = "î˜•", color = "#C1F12E" }
"bmp" = { icon = "î˜", color = "#a074c4" }
"c" = { icon = "î˜", color = "#599eff" }
"c++" = { icon = "î˜", color = "#f34b7d" }
"cbl" = { icon = "âš™", color = "#005ca5" }
"cc" = { icon = "î˜", color = "#f34b7d" }
"cfg" = { icon = "î£", color = "#ECECEC" }
"clj" = { icon = "î¨", color = "#8dc149" }
"cljc" = { icon = "î¨", color = "#8dc149" }
"cljs" = { icon = "îª", color = "#519aba" }
"cljd" = { icon = "îª", color = "#519aba" }
"cmake" = { icon = "î˜•", color = "#6d8086" }
"cob" = { icon = "âš™", color = "#005ca5" }
"cobol" = { icon = "âš™", color = "#005ca5" }
"coffee" = { icon = "î˜›", color = "#cbcb41" }
"conf" = { icon = "î˜•", color = "#6d8086" }
"config.ru" = { icon = "î‘", color = "#701516" }
"cp" = { icon = "î˜", color = "#519aba" }
"cpp" = { icon = "î˜", color = "#519aba" }
"cpy" = { icon = "âš™", color = "#005ca5" }
"cr" = { icon = "î‰" }
"cs" = { icon = "ï š", color = "#596706" }
"csh" = { icon = "î•", color = "#4d5a5e" }
"cson" = { icon = "î˜‹", color = "#cbcb41" }
"css" = { icon = "î‰", color = "#42a5f5" }
"csv" = { icon = "ïœ˜", color = "#89e051" }
"cxx" = { icon = "î˜", color = "#519aba" }
"d" = { icon = "î¯", color = "#427819" }
"dart" = { icon = "î˜", color = "#03589C" }
"db" = { icon = "îœ†", color = "#dad8d8" }
"desktop" = { icon = "ï„ˆ", color = "#563d7c" }
"diff" = { icon = "îœ¨", color = "#41535b" }
"doc" = { icon = "ïœ«", color = "#185abd" }
"dockerfile" = { icon = "î°", color = "#384d54" }
"drl" = { icon = "îŠŒ", color = "#ffafaf" }
"dropbox" = { icon = "îœ‡", color = "#0061FE" }
"dump" = { icon = "îœ†", color = "#dad8d8" }
"edn" = { icon = "îª", color = "#519aba" }
"eex" = { icon = "î˜­", color = "#a074c4" }
"ejs" = { icon = "î˜", color = "#cbcb41" }
"elm" = { icon = "î˜¬", color = "#519aba" }
"epp" = { icon = "î˜±", color = "#FFA61A" }
"erb" = { icon = "î˜", color = "#701516" }
"erl" = { icon = "î±", color = "#B83998" }
"ex" = { icon = "î˜­", color = "#a074c4" }
"exs" = { icon = "î˜­", color = "#a074c4" }
"f#" = { icon = "î§", color = "#519aba" }
"favicon.ico" = { icon = "î˜£", color = "#cbcb41" }
"fnl" = { icon = "ğŸŒœ", color = "#fff3d7" }
"fish" = { icon = "î•", color = "#4d5a5e" }
"fs" = { icon = "î§", color = "#519aba" }
"fsi" = { icon = "î§", color = "#519aba" }
"fsscript" = { icon = "î§", color = "#519aba" }
"fsx" = { icon = "î§", color = "#519aba" }
"gd" = { icon = "î˜•", color = "#6d8086" }
"gemspec" = { icon = "î‘", color = "#701516" }
"gif" = { icon = "î˜", color = "#a074c4" }
"git" = { icon = "îœ‚", color = "#F14C28" }
"glb" = { icon = "ï†²", color = "#FFB13B" }
"go" = { icon = "î˜§", color = "#519aba" }
"godot" = { icon = "î£", color = "#6d8086" }
"graphql" = { icon = "ïˆ", color = "#e535ab" }
"gruntfile" = { icon = "î˜‘", color = "#e37933" }
"gulpfile" = { icon = "î˜", color = "#cc3e44" }
"h" = { icon = "ïƒ½", color = "#a074c4" }
"haml" = { icon = "î˜", color = "#eaeae1" }
"hbs" = { icon = "î˜", color = "#f0772b" }
"heex" = { icon = "î˜­", color = "#a074c4" }
"hh" = { icon = "ïƒ½", color = "#a074c4" }
"hpp" = { icon = "ïƒ½", color = "#a074c4" }
"hrl" = { icon = "î±", color = "#B83998" }
"hs" = { icon = "î˜Ÿ", color = "#a074c4" }
"htm" = { icon = "î˜", color = "#e34c26" }
"html" = { icon = "îœ¶", color = "#e44d26" }
"hxx" = { icon = "ïƒ½", color = "#a074c4" }
"ico" = { icon = "î˜", color = "#cbcb41" }
"import" = { icon = "ïƒ†", color = "#ECECEC" }
"ini" = { icon = "î˜•", color = "#6d8086" }
"java" = { icon = "îœ¸", color = "#cc3e44" }
"jl" = { icon = "î˜¤", color = "#a270ba" }
"jpeg" = { icon = "î˜", color = "#a074c4" }
"jpg" = { icon = "î˜", color = "#a074c4" }
"js" = { icon = "î˜Œ", color = "#cbcb41" }
"json" = { icon = "î˜‹", color = "#cbcb41" }
"json5" = { icon = "ï¬¥", color = "#cbcb41" }
"jsx" = { icon = "î˜¥", color = "#519aba" }
"ksh" = { icon = "î•", color = "#4d5a5e" }
"kt" = { icon = "î˜´", color = "#F88A02" }
"kts" = { icon = "î˜´", color = "#F88A02" }
"leex" = { icon = "î˜­", color = "#a074c4" }
"less" = { icon = "î˜”", color = "#563d7c" }
"lhs" = { icon = "î˜Ÿ", color = "#a074c4" }
"license" = { icon = "î˜Š", color = "#cbcb41" }
"lua" = { icon = "î˜ ", color = "#51a0cf" }
"luau" = { icon = "î˜ ", color = "#51a0cf" }
"makefile" = { icon = "î˜•", color = "#6d8086" }
"markdown" = { icon = "î˜‰", color = "#d74c4c" }
"material" = { icon = "ïŸ´", color = "#B83998" }
"md" = { icon = "î˜‰", color = "#d74c4c" }
"mdx" = { icon = "î˜‰", color = "#d74c4c" }
"mint" = { icon = "ï ©", color = "#87c095" }
"mix.lock" = { icon = "î˜­", color = "#a074c4" }
"mjs" = { icon = "î˜Œ", color = "#f1e05a" }
"ml" = { icon = "Î»", color = "#e37933" }
"mli" = { icon = "Î»", color = "#e37933" }
"mo" = { icon = "âˆ", color = "#9772FB" }
"mustache" = { icon = "î˜", color = "#e37933" }
"nim" = { icon = "ğŸ‘‘", color = "#f3d400" }
"nix" = { icon = "ïŒ“", color = "#7ebae4" }
"node_modules" = { icon = "îœ˜", color = "#E8274B" }
"opus" = { icon = "ïœ¢", color = "#F88A02" }
"otf" = { icon = "ï€±", color = "#ECECEC" }
"package.json" = { icon = "îœ", color = "#e8274b" }
"package-lock.json" = { icon = "îœ", color = "#7a0d21" }
"pck" = { icon = "ï’‡", color = "#6d8086" }
"pdf" = { icon = "ïœ¤", color = "#b30b00" }
"php" = { icon = "î˜ˆ", color = "#a074c4" }
"pl" = { icon = "î©", color = "#519aba" }
"pm" = { icon = "î©", color = "#519aba" }
"png" = { icon = "î˜", color = "#a074c4" }
"pp" = { icon = "î˜±", color = "#FFA61A" }
"ppt" = { icon = "ïœ¦", color = "#cb4a32" }
"pro" = { icon = "î¡", color = "#e4b854" }
"Procfile" = { icon = "î˜‡", color = "#a074c4" }
"ps1" = { icon = "î•", color = "#4d5a5e" }
"psb" = { icon = "î¸", color = "#519aba" }
"psd" = { icon = "î¸", color = "#519aba" }
"py" = { icon = "î˜†", color = "#ffbc03" }
"pyc" = { icon = "î˜†", color = "#ffe291" }
"pyd" = { icon = "î˜†", color = "#ffe291" }
"pyo" = { icon = "î˜†", color = "#ffe291" }
"query" = { icon = "îˆœ", color = "#90a850" }
"r" = { icon = "ï³’", color = "#358a5b" }
"rake" = { icon = "î‘", color = "#701516" }
"rakefile" = { icon = "î‘", color = "#701516" }
"rb" = { icon = "î‘", color = "#701516" }
"rlib" = { icon = "î¨", color = "#dea584" }
"rmd" = { icon = "î˜‰", color = "#519aba" }
"rproj" = { icon = "ï«…", color = "#358a5b" }
"rs" = { icon = "î¨", color = "#dea584" }
"rss" = { icon = "î˜™", color = "#FB9D3B" }
"sass" = { icon = "î˜ƒ", color = "#f55385" }
"sbt" = { icon = "îœ·", color = "#cc3e44" }
"scala" = { icon = "îœ·", color = "#cc3e44" }
"scm" = { icon = "ï¬¦" }
"scss" = { icon = "î˜ƒ", color = "#f55385" }
"sh" = { icon = "î•", color = "#4d5a5e" }
"sig" = { icon = "Î»", color = "#e37933" }
"slim" = { icon = "î˜", color = "#e34c26" }
"sln" = { icon = "îœŒ", color = "#854CC7" }
"sml" = { icon = "Î»", color = "#e37933" }
"sql" = { icon = "îœ†", color = "#dad8d8" }
"sqlite" = { icon = "îœ†", color = "#dad8d8" }
"sqlite3" = { icon = "îœ†", color = "#dad8d8" }
"styl" = { icon = "î˜€", color = "#8dc149" }
"sublime" = { icon = "îª", color = "#e37933" }
"suo" = { icon = "îœŒ", color = "#854CC7" }
"sv" = { icon = "ï¡š", color = "#019833" }
"svelte" = { icon = "ï‰ ", color = "#ff3e00" }
"svh" = { icon = "ï¡š", color = "#019833" }
"svg" = { icon = "ï°Ÿ", color = "#FFB13B" }
"swift" = { icon = "î•", color = "#e37933" }
"t" = { icon = "î©", color = "#519aba" }
"tbc" = { icon = "ï¯‘", color = "#1e5cb3" }
"tcl" = { icon = "ï¯‘", color = "#1e5cb3" }
"terminal" = { icon = "ï’‰", color = "#31B53E" }
"tex" = { icon = "ï­¨", color = "#3D6117" }
"tf" = { icon = "îŠ¦", color = "#5F43E9" }
"tfvars" = { icon = "ï…›", color = "#5F43E9" }
"toml" = { icon = "î˜•", color = "#6d8086" }
"tres" = { icon = "îœ†", color = "#cbcb41" }
"ts" = { icon = "î˜¨", color = "#519aba" }
"tscn" = { icon = "ï¢€", color = "#a074c4" }
"tsx" = { icon = "îº", color = "#519aba" }
"twig" = { icon = "î˜œ", color = "#8dc149" }
"txt" = { icon = "ïœ˜", color = "#89e051" }
"v" = { icon = "ï¡š", color = "#019833" }
"vh" = { icon = "ï¡š", color = "#019833" }
"vhd" = { icon = "ï¡š", color = "#019833" }
"vhdl" = { icon = "ï¡š", color = "#019833" }
"vim" = { icon = "î˜«", color = "#019833" }
"vue" = { icon = "ïµ‚", color = "#8dc149" }
"webmanifest" = { icon = "î˜‹", color = "#f1e05a" }
"webp" = { icon = "î˜", color = "#a074c4" }
"webpack" = { icon = "ï°©", color = "#519aba" }
"xcplayground" = { icon = "î•", color = "#e37933" }
"xls" = { icon = "ïœš", color = "#207245" }
"xml" = { icon = "ïª¿", color = "#e37933" }
"xul" = { icon = "î…", color = "#e37933" }
"yaml" = { icon = "î˜•", color = "#6d8086" }
"yml" = { icon = "î˜•", color = "#6d8086" }
"zig" = { icon = "ïƒ§", color = "#f69a1b" }
"zsh" = { icon = "î•", color = "#89e051" }
"sol" = { icon = "ï²¹", color = "#519aba" }
".env" = { icon = "ï‘¢", color = "#faf743" }
"prisma" = { icon = "ï¨µ" }
"lock" = { icon = "ï„¾", color = "#bbbbbb" }
"log" = { icon = "î©»" }
