[book]
authors = ["Bla≈æ Hrastnik"]
language = "en"
src = "src"

[output.html]
cname = "docs.silicon-editor.com"
default-theme = "colibri"
preferred-dark-theme = "colibri"
git-repository-url = "https://github.com/silicon-editor/silicon"
edit-url-template = "https://github.com/silicon-editor/silicon/edit/master/book/{path}"
additional-css = ["custom.css"]

[output.html.search]
use-boolean-and = true
