# Publish the Nix flake outputs to Cachix
name: Cachix
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Flake
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install nix
      uses: cachix/install-nix-action@v18

    - name: Authenticate with Cachix
      uses: cachix/cachix-action@v12
      with:
        name: helix
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Build nix flake
      run: nix build -L
